schema_version = "1.0.0"

id = "AddCameraRigged"
version = "1.0.0"
name = "AddCameraRigged"
tagline = "Add a rigged camera"
maintainer = "Netherby"
type = "add-on"
tags = ["Camera"]

blender_version_min = "5.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
   "2025-26 Dancing Fortune Software",
]